### PR TITLE
First draft, ready for PR

### PR DESCRIPTION
**Pull request by Joosty**
This is the **Forces, Moments, and Torques** section of the **Forces, Moments, and Momenta** chapter. Transcription, wording edits and figure trimming are complete. Any issues let me know and will fix asap as usual.

### CODE REVIEW

**Comment by angadhn** [comment]
The force term needs to be in bold $\bf F$.
image

**Comment by angadhn** [comment]
Remove $\times$ after $d$

image

**Comment by angadhn** [comment]
My bad in the handwritten notes for this one; could you make all the $r_i$ and $v_i$ below into ${\bf r}_i$ and ${\bf v}_i$ (use `{\bf r}_i` and `{\bf v}_i` so that the $i$ is in italics.)

image

**Comment by angadhn** [comment]
Again, my bad in the handwritten notes for this one; could you make $F_i$ below into ${\bf F}_i$.

image

**Comment by Joosty** [comment]
should all be sorted :)

**Comment by angadhn** [comment]
The need for speed....

**Pull request merged**
