### PR TITLE
Momentum linear and angular - transcription

### PR DESCRIPTION
**Pull request by Joosty**
This branch has updates to the 'Momentum linear and angular' section of the textbook. Handwritten notes have been transcribed with small changes to the text to help with flow. Images have been cropped or removed.

### CODE REVIEW

**Comment by angadhn** [comment]
There are extraneous $$ in both lines of the image below.

Use inline math for the first notation and the equation definition notation in a new line:
image

**Comment by angadhn** [comment]
Unsure why this is the case for this image but might be worth double checking: 
image

**Comment by angadhn** [comment]
Make omega (and alpha, in the next notebook) boldface by using 
```^N{\boldsymbol\omega}^B``` which should give $\boldsymbol{\omega}$

image

**Comment by angadhn** [comment]
Another pedantic comment coming but instead of $dm$, use ```\mathrm{d}m``` to get $\mathrm{d}m$.

**Comment by angadhn** [comment]
Something weird happening here:
image

**Comment by angadhn** [comment]
For sake a of readability put a ```\cdot``` between the inertia matrix and angular velocity terms. otherwise those superscripts end up looking janky.
image

**Comment by Joosty** [comment]
I will get working on the errors now. I was unsure of how to view the file in the format displayed on the web book ahead of time so missed these issues. How would you recommend I do view it to avoid future issues?

**Comment by angadhn** [comment]
> I will get working on the errors now. I was unsure of how to view the file in the format displayed on the web book ahead of time so missed these issues. How would you recommend I do view it to avoid future issues?

I wouldn't be so harsh as to call them errors :-) I think I will be the bottleneck, unless you get linux running on your computer. 

There is a way to [build the work in windows](https://jupyterbook.org/en/stable/advanced/windows.html)  which will help you preview the book but that text does not inspire confidence in me :-)

**Comment by Joosty** [comment]
Okay I'll work on the raised issues and then submit again. 

Second question..

Did you want the whole forces, moments and momentia section of the textbook done? I was under the impression that you wanted the sections highlighted in the pic attached. Let me know and I can go back (I am actively working on teh dynamics section)

Cheers :) 

image

**Comment by angadhn** [comment]
Finish the chapter in the dynamics section- I don't think the problems in it need any work.

Then come back to the first chapter "forces, moments and torque"- I think that could use the same treatment to LaTeX.

Also, do you feel this activity (which is definitely great for the text!) is adding to your understanding/filling gaps or exposing new gaps following last week's meeting?

**Comment by Joosty** [comment]
Sounds good. I think it's valuable to go back over everything just to regain/reinforce some fundamental understanding that I may have lost in the past year - definitely happy I'm doing it. Also good to do something that makes my GitHub look active for potential interviews and so fourth in the coming year :)

**Comment by Joosty** [comment]
I have now corrected the issues raised as well as a few spelling issues. Hope this is all okay. As before feel free to let me know of any further issues.

**Comment by angadhn** [comment]
image

Still an issue here- and also using arrows on the vector

**Comment by Joosty** [comment]
Hmm, seem to be having issues with this.  This is what I am switching it to. If this doesn't work I will just remove the attention quote box. Will push now. 

````{attention}
Prior to dealing with this term, note:

$$\int_m{\mathbf{{r}}\mathrm{d}m} = 0$$

<div style="text-align: center;"> and, </div>

$$\mathbf{{r}} = \mathbf{r}^{OP}$$

````

**Comment by angadhn** [comment]
Okay- did you look into building books locally for yourself?

**Comment by angadhn** [comment]
Looks fine now, methinks.
image

**Comment by Joosty** [comment]
> Okay- did you look into building books locally for yourself?

I did look very briefly but have not taken action, will look more into it today and see if I can get it working. It would be very helpful.

**Comment by angadhn** [comment]
No worries- all looks great and I have gone ahead and merged this. Thank you for your service! Pints incoming in a week or so.

**Pull request merged**
