### PR TITLE
Inertia-2: remove unneeded hand calcs that don't render

### PR DESCRIPTION
**Pull request by Joosty**
**second attempt at inertia-2, I originally messed up and lumped the inertia 1 and 2 changes into one PR but this has now been closed and fixed into two separate PR's for inertia 1 & 2**

All this PR does is remove unneeded hand calcs as they have been transcribed prior - in the current state they also don't render which makes the book look messy.

see image below 
image

### CODE REVIEW

**Comment by angadhn** [comment]
@Joosty just seeing this. Should I close the other one or are they different changes?

**Comment by Joosty** [comment]
@angadhn the two open PR's are different changes - I have closed the rogue one.

**Comment by angadhn** [comment]
@Joosty please update both branches. I added an Action to check syncs when PRs are opened. That was not part of this text. Sorry!

**Comment by Joosty** [comment]
@angadhn have updated both branches, hope this is okay :)

**Comment by angadhn** [comment]
@Joosty sorry. You might need to do this once more on both branches. :(

**Comment by Joosty** [comment]
@angadhn I don't seem to be able to. See below the sync option for both branches.

image
image

**Pull request merged**
