### PR TITLE
inertia-1 transcription, wording and images edits

### PR DESCRIPTION
**Pull request by Joosty**
I hope you don't mind me taking the liberty to do some transcription work on the **inertia** chapter (particularly the **Mass/Inertia Scalars** file) that I noticed needed to be done. Also fixed wording and images.

I saw an issue in the **Theorems for Computing Inertia Matrix** file so there will be a separate PR to follow.

Cheers,
Joost

### CODE REVIEW

**Comment by angadhn** [comment]
Go for it! If the entire world was like you, then we'd probably already have more orbiting habitats and, hell, maybe even a nascent civilisation on Mars.

**Comment by angadhn** [comment]
might need to resync this as I just merged the other.. unsure if that is actually needed. I think I should revisit my git knowledge..

**Comment by Joosty** [comment]
resynced just in case.

**Comment by angadhn** [comment]
Right- so in this lecture, the all the $\{bf P}_i$ need to be $\{bf p}_i$. This is also when you expand them.

There are also cases where you have $\{bf P}$, which needs to be $\{bf p}$.

This is why handwritten stuff is bad, I guess 😄

**Comment by Joosty** [comment]
Will get going on that now, thanks for letting me know :)

**Comment by Joosty** [comment]
@angadhn should be done :) let me know if i missed anything, will be back in a few hours :)

**Pull request merged**
